"use client";

import "./globals.css";
import { ThemeProvider } from "next-themes";
import Link from "next/link";
// import type { Metadata } from "next";
import { Poppins } from "next/font/google";

import { Toaster } from "react-hot-toast";

// Components
import { Navbar } from "../components/Navbar";
import { Footer } from "@/components/Footer";
import { Metadata } from "../components/Metadata";

// Context
import { UserProvider } from "@/context/UserContext";

const poppins = Poppins({ subsets: ["latin"], weight: "400" });

// export const metadata: Metadata = {
// 	title: "Midara",
// 	description: "Generated by create next app",
// };

interface IPropsChildren {
	children: React.ReactNode;
}

export default function RootLayout({ children }: IPropsChildren) {
	return (
		<html lang="pt-BR">
			<head>
				<Link rel="icon" href="/favicon.png" type="image/png" />
				<Link
					href="https://cdn.jsdelivr.net/npm/daisyui@3.7.7/dist/full.css"
					rel="stylesheet"
					type="text/css"
				/>
			</head>
			<body className={poppins.className}>
				<ThemeProvider enableSystem={true} attribute="class">
					<UserProvider>
						<Metadata
							title="Midara Hentai"
							description="Descrição global"
						/>
						<Navbar />
						<Toaster
							position="bottom-center"
							reverseOrder={false}
							toastOptions={{ duration: 2000 }}
						/>
						{children}
						<Footer />
					</UserProvider>
				</ThemeProvider>
			</body>
		</html>
	);
}
